
server:
  port: 8999

spring:
  application:
    name: ticket-service
#  config:
#    import: optional:configserver:http://localhost:9296
  data:
    mongodb:
      host: localhost
      port: 27017
      database: ticket-ticket
