
server:
  port: 9011

spring:
  application:
    name: ticket-service
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
#  config:
#    import: optional:configserver:http://localhost:9296
  data:
    mongodb:
      host: localhost
      port: 27017
      database: TicketService