server:
  port: 8005

spring:
  application:
    name: payment-service
  data:
    mongodb:
      url: mongodb+srv://nsonbao0601:alNlxNVoma7mgxKo@cluster0.hknjigi.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
#      username: nsonbao0601
#      password: alNlxNVoma7mgxKo
#      host: cluster0.hknjigi.mongodb.net
      database: ticket


eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
jwt:
  secret: BvPHGM8C0ia4uOuxxqPD5DTbWC9F9TWvPStp3pb7ARo0oK2mJ3pd3YG4lxA9i8bj6OTbadwezxgeEByY
  expiration: 20400


vnpay:
  terminalId: LBSLHTAQ
  secret: JHFEEHQQRRLBEMVMSDGAGKZREGVFBZXR
  vnpayUrl:  https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
  returnUrl: http://localhost:3000/vnpay/return