server:
  port: 9002

spring:
  application:
    name: user-service
#  config:
#    import: optional:configserver:http://localhost:9296
  data:
    mongodb:
      host: localhost
      port: 27017
      database: ticket-user

jwt:
  secret: BvPHGM8C0ia4uOuxxqPD5DTbWC9F9TWvPStp3pb7ARo0oK2mJ3pd3YG4lxA9i8bj6OTbadwezxgeEByY
  expiration: 86400