server:
  port: 9002

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: user-service
#  config:
#    import: optional:configserver:http://localhost:9296
  data:
    mongodb:
      uri: mongodb+srv://congtuan0104:12345@cluster-mongo-test.6rwo2y1.mongodb.net/ticket-user

jwt:
  secret: BvPHGM8C0ia4uOuxxqPD5DTbWC9F9TWvPStp3pb7ARo0oK2mJ3pd3YG4lxA9i8bj6OTbadwezxgeEByY
  expiration: 86400