server:
  port: 9297
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/congtuan0104/ticket-backend-config.git
          clone-on-start: true
          default-label: main
