
server:
  port: 9011

spring:
  application:
    name: ticket-service
#  config:
#    import: optional:configserver:http://localhost:9296
  data:
    mongodb:
      uri: mongodb+srv://huynhtrongnghia10012000:18120478@ticket-service.awafma7.mongodb.net/?retryWrites=true&w=majority&appName=ticket-
      database: ticket-service